### ISSUE TITLE
Use sparse matrix as input

### ISSUE THREAD

**Issue by sshen82** [PeterZZQ/scDART#4]
Hi,
Thank you for this great method! I have a question: can I use sparse matrix for ATAC-seq data and gene activity matrix as input? My data is different from the conventional ATAC-seq data, and it actually has much more features. I tried to directly use the dense matrix, but doesn't work.

Yours sincerely,
Siqi Shen

**Comment by PeterZZQ** [comment]
Hi,

For scATAC-seq matrix, you might save it into the sparse format, but you will still have to transform it back to a dense PyTorch matrix before loading it into the encoder network. Maybe you can first filter out some regions according to the gene expression matrix (use only the regions that lie within 2000 upstream of the genes on the genome), or you can separate the genome into larger bins (e.g. 100,000 bp sized bin as common practice) and sum the region count within each bin. Using larger bins can significantly reduce the dimension, but it will still keep enough information for most of the downstream analysis. 

If you insist on training on the original dataset, you might need to think of a way to rewrite the `dataloader` function in scDART. Instead of automatically separate mini-batches using `dataloader` from the dense matrix, you can separate sparse mini-batches from the sparse matrix once a time and only transform the sparse mini-batch to dense each time to save memory. It might not be trivial and might significantly increase the training time. I don't know if there are any read-to-use packages that can help with training on sparse data matrices, you can search for that too.
